# Generated by Django 5.1.6 on 2025-02-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(limit_choices_to=models.Q(('user__is_superuser', True)), on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.profile'),
        ),
    ]
